UI talks refactor
Solar-Punk-Ltd/DevconAgora pull request #63
Opened 2024-10-24 14:36 UTC by rolandlor

2024-10-24 15:29 UTC, bosi95 requested changes

2024-10-24 15:29 UTC, bosi95 commented on package.json
> +    "@solarpunkltd/comment-system-ui": "file:/Users/seresroland/Desktop/DEVCONAPP/SwarmCommentSystem/comment-system-ui",
set to version 0.0.13
make sure that the comment-ui npm package is first published

2024-10-24 17:45 UTC, ottpeter approved these changes

2024-10-25 11:51 UTC, bosi95 approved these changes

2024-10-25 11:59 UTC, merged